name: netnerve
description: Fancy network flutter library
version: 0.2.0

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.14
  flutter_inappwebview: ^6.0.0-beta.22
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
