name: netnerve
description: Fancy network flutter library
version: 0.2.5

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio:
  flutter_inappwebview: ^6.0.0-beta.32
  path_provider_platform_interface:
  path_provider:
  path:
  plugin_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
